// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: video_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`      // The raw image bytes (JPEG/PNG)
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // To sync results back to the correct frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_video_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_video_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_video_service_proto_rawDescGZIP(), []int{0}
}

func (x *VideoFrame) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VideoFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AnalysisResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    string                 `protobuf:"bytes,1,opt,name=prediction,proto3" json:"prediction,omitempty"` // e.g., "Hand Open", "Face Detected"
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Return the timestamp so Frontend knows which frame this is for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_video_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_video_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_video_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResult) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

func (x *AnalysisResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalysisResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_video_service_proto protoreflect.FileDescriptor

const file_video_service_proto_rawDesc = "" +
	"\n" +
	"\x13video_service.proto\x12\x05video\"D\n" +
	"\n" +
	"VideoFrame\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"n\n" +
	"\x0eAnalysisResult\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\tR\n" +
	"prediction\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2N\n" +
	"\x0eVideoProcessor\x12<\n" +
	"\fProcessVideo\x12\x11.video.VideoFrame\x1a\x15.video.AnalysisResult(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_video_service_proto_rawDescOnce sync.Once
	file_video_service_proto_rawDescData []byte
)

func file_video_service_proto_rawDescGZIP() []byte {
	file_video_service_proto_rawDescOnce.Do(func() {
		file_video_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_service_proto_rawDesc), len(file_video_service_proto_rawDesc)))
	})
	return file_video_service_proto_rawDescData
}

var file_video_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_video_service_proto_goTypes = []any{
	(*VideoFrame)(nil),     // 0: video.VideoFrame
	(*AnalysisResult)(nil), // 1: video.AnalysisResult
}
var file_video_service_proto_depIdxs = []int32{
	0, // 0: video.VideoProcessor.ProcessVideo:input_type -> video.VideoFrame
	1, // 1: video.VideoProcessor.ProcessVideo:output_type -> video.AnalysisResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_service_proto_init() }
func file_video_service_proto_init() {
	if File_video_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_service_proto_rawDesc), len(file_video_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_service_proto_goTypes,
		DependencyIndexes: file_video_service_proto_depIdxs,
		MessageInfos:      file_video_service_proto_msgTypes,
	}.Build()
	File_video_service_proto = out.File
	file_video_service_proto_goTypes = nil
	file_video_service_proto_depIdxs = nil
}
