// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: video_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoProcessor_ProcessVideo_FullMethodName = "/video.VideoProcessor/ProcessVideo"
)

// VideoProcessorClient is the client API for VideoProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoProcessorClient interface {
	// Bidirectional stream: Stream frames in, stream results out
	ProcessVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VideoFrame, AnalysisResult], error)
}

type videoProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoProcessorClient(cc grpc.ClientConnInterface) VideoProcessorClient {
	return &videoProcessorClient{cc}
}

func (c *videoProcessorClient) ProcessVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VideoFrame, AnalysisResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoProcessor_ServiceDesc.Streams[0], VideoProcessor_ProcessVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VideoFrame, AnalysisResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoProcessor_ProcessVideoClient = grpc.BidiStreamingClient[VideoFrame, AnalysisResult]

// VideoProcessorServer is the server API for VideoProcessor service.
// All implementations must embed UnimplementedVideoProcessorServer
// for forward compatibility.
type VideoProcessorServer interface {
	// Bidirectional stream: Stream frames in, stream results out
	ProcessVideo(grpc.BidiStreamingServer[VideoFrame, AnalysisResult]) error
	mustEmbedUnimplementedVideoProcessorServer()
}

// UnimplementedVideoProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoProcessorServer struct{}

func (UnimplementedVideoProcessorServer) ProcessVideo(grpc.BidiStreamingServer[VideoFrame, AnalysisResult]) error {
	return status.Error(codes.Unimplemented, "method ProcessVideo not implemented")
}
func (UnimplementedVideoProcessorServer) mustEmbedUnimplementedVideoProcessorServer() {}
func (UnimplementedVideoProcessorServer) testEmbeddedByValue()                        {}

// UnsafeVideoProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoProcessorServer will
// result in compilation errors.
type UnsafeVideoProcessorServer interface {
	mustEmbedUnimplementedVideoProcessorServer()
}

func RegisterVideoProcessorServer(s grpc.ServiceRegistrar, srv VideoProcessorServer) {
	// If the following call panics, it indicates UnimplementedVideoProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoProcessor_ServiceDesc, srv)
}

func _VideoProcessor_ProcessVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoProcessorServer).ProcessVideo(&grpc.GenericServerStream[VideoFrame, AnalysisResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoProcessor_ProcessVideoServer = grpc.BidiStreamingServer[VideoFrame, AnalysisResult]

// VideoProcessor_ServiceDesc is the grpc.ServiceDesc for VideoProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoProcessor",
	HandlerType: (*VideoProcessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessVideo",
			Handler:       _VideoProcessor_ProcessVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "video_service.proto",
}
